### ISSUE TITLE
Terminates zsh when typing space

### ISSUE THREAD

**Issue by bmedicke** [hlissner/zsh-autopair#15]
I just updated to a01f074 and now every time I type a space the current shell exits. Both when space is the first character and when it follows after any other. 

I update every couple of days so it should be from a recent commit. I have disabled all other zplug plugins but it still occurs. I do have a rather large `.zshrc`, so let me know if I should try again with a minimal config file.

```sh
$ zplug --version
2.4.1
$ zsh --version
zsh 5.4.2 (x86_64-apple-darwin17.0.0)
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.13
BuildVersion:   17A365
```

As an aside: zplug's `nice` has been deprecated, so I'm using 
`zplug "hlissner/zsh-autopair", defer:2` instead. I can send you a pull request if you'd like to change it.

Edit:

b0a995a is the last commit that's working fine for me, so the bug was introduced in e3f9e30: 
"Refactor & more generalized widget fallthrough #14"

For now I have pinned that commit with:
`zplug "hlissner/zsh-autopair", defer:2, at:b0a995a`

**Comment by akatrevorjay** [comment]
I also have this issue on Ubuntu Artful and Zesty

**Comment by hlissner** [comment]
I _think_ this is related to #14, which I've just pushed a fix for. Please update and let me know. If you still have trouble, please include the output of the following:

+ `setopt`
+ `echo ${(@kv)AUTOPAIR_PAIRS}`
+ `echo ${(@kv)AUTOPAIR_FALLBACKS}`

**Comment by bmedicke** [comment]
That fixed it, thank you so much! In case you're curious here's the output anyway:

```sh
$ setopt
alwaystoend
autopushd
completeinword
noflowcontrol
histignorespace
incappendhistory
interactive
interactivecomments
login
monitor
promptsubst
sharehistory
shinstdin
zle
$ echo ${(@kv)AUTOPAIR_PAIRS}

" " { } ' ' ( ) [ ] ` `
$ echo ${(@kv)AUTOPAIR_FALLBACKS}

```
