### ISSUE TITLE
Auto delete delimiters with Alt + Backspace

### ISSUE THREAD

**Issue by mawkler** [hlissner/zsh-autopair#18]
I love this plugin so much. But one thing that sorta bothers me is this:

Typing `"` once gives me this `"|"` (where `|` is the cursor).

Pressing `Backspace` once removes both quotes.

I feel like `Alt + Backspace` (for removing whole word) should have the same behviour as just `Backspace`, which it currently doesn't. `Alt + Backspace` currently only removes the left `"`.

**Comment by hlissner** [comment]
As of #34, this should be resolved. Thanks for bringing it to my attention!
