### ISSUE TITLE
don't collapse ` | ` by itself

### ISSUE THREAD

**Issue by plexigras** [hlissner/zsh-autopair#19]
`[ | ]` and then pressing `<bs>` should result in `[]` but `this is | i a test` and then pressing `<bs>` should not result in `this isa test` but `this is a test` instead.

**Comment by hlissner** [comment]
Sorry for the _tremendously_ late response. Is this still an issue? I cannot reproduce either case in 5.7.1 with only autopair installed.

**Comment by hlissner** [comment]
My bad, I was using the develop branch, which already had 34a8bca on it. This should be resolved. Let me know if that isn't the case and I'll reopen this. Thanks for bringing it to my attention!
