### ISSUE TITLE
Add to Homebrew

### ISSUE THREAD

**Issue by erusev** [hlissner/zsh-autopair#21]
would love to be able to install `zsh-autopair` with Homebrew

**Comment by erusev** [comment]
until then, i'd love to know what'd be the recommended way to install it - do i clone it to `~/.zsh-autopair` or somewhere else, i'd love some advice on this

**Comment by hlissner** [comment]
I'm not knowledgeable about the submission process for homebrew and don't have time to look into it myself, at the moment. For the time being I have expanded the install instructions to answer your question, in aab8c3f.

**Comment by chrisgrieser** [comment]
found this plugin via homebrew, so I assume someone has added it already.
