### ISSUE TITLE
Hi! Not about zsh-autopair at all, but about the Equestria maps you made 11 years ago

### ISSUE THREAD

**Issue by Vector-Graphics** [hlissner/zsh-autopair#32]
Do you happen to have any of the older versions (specifically revision 6) on your computer still? I'm looking to archive all the versions of your map (in order to help preserve MLP fandom history) and currently I don't have version 6 (I have two versions of revision 5, as well as revision 7 and of course the public revisions 1, 2, 3, 4, and 8, and so revision 6 is an annoying gap in the timeline.)

**Comment by hlissner** [comment]
Sorry to say I don't have any but the latest revision anymore. In any case, please email me (address is in my github profile) instead of posting issues to my repos.
