### ISSUE TITLE
Can I add install instruction for Oh My Zsh users?

### ISSUE THREAD

**Issue by s4my** [hlissner/zsh-autopair#37]
Can I submit a PR adding install instruction of [Oh My Zsh](https://ohmyz.sh/) users.

**Comment by happyTonakai** [comment]
Hi, please do it. I'm using oh my zsh and waiting for it.

**Comment by happyTonakai** [comment]
I clone the repo in the plugin directory as
`git clone https://github.com/hlissner/zsh-autopair.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autopair`
and execute
```
source ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autopair/autopair.zsh
autopair-init
```
Add it to plugins
```
plugins=(... zsh-autopair)
```

and add `source ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autopair/autopair.zsh` to .zshrc as well. But it only works if I `source ~/.zshrc`. When I launch a new zsh it doesn't work.

**Comment by s4my** [comment]
> Hi, please do it. I'm using oh my zsh and waiting for it.

Here you go #38
