### ISSUE TITLE
autopair don't work with vi-mode open

### ISSUE THREAD

**Issue by AhJi26** [hlissner/zsh-autopair#39]
### What did you expect to happen?

I'm using this script as a plugin of oh-my-zsh, but as long as I enable the vi-mode plugin, this plugin just stop working.

### What actually happened?

as above

### Steps to reproduce

1. install oh-my-zsh
2. install this project as plugin
3. enable oh-my-zsh built-in plugin vi-mode

### Package commit

34a90da77a00b152b12e908504b5f41f45340b15

**Comment by hlissner** [comment]
I don't use oh-my-zsh, so I can't help here, but it seems [others are using it without issue](https://github.com/hlissner/zsh-autopair/pull/38). I suggest tinkering with the load order of your plugins, because other plugins could be overwriting this package's hooks.
