### ISSUE TITLE
Invalid local array initialization

### ISSUE THREAD

**Issue by 1ambda** [hlissner/zsh-autopair#5]
I am using `zsh 5.0.8 (x86_64-apple-darwin15.0)` and load `zsh-auto-pair` with `zplug`.

The error message is, 

```zsh
/Users/1ambda/.zplug/repos/hlissner/zsh-autopair/autopair.zsh:150: unknown file attribute: )
```

The code in [autopair.zsh line #150](https://github.com/hlissner/zsh-autopair/blob/8cc544e5c802389b2897588ab7056ec7a1c283b8/autopair.zsh#L150) should be

```
// before
local l=(')', '}', ']', '>')

// should be: http://stackoverflow.com/questions/14917501/local-arrays-in-zsh
local -a l
l=(')', '}', ']', '>')
```

Also, [autopair.zsh line #40](https://github.com/hlissner/zsh-autopair/blob/8cc544e5c802389b2897588ab7056ec7a1c283b8/autopair.zsh#L40) should be modified, otherwise it will throw the `ap-next-to-boundary-p:1: number expected` error

```
// before
local groups=(all)

// should be: 
local -a groups
groups=(all)
```

Thanks for making the great terminal tool :)

**Comment by hlissner** [comment]
I was wondering how to fix that! Thanks for the help!
