### ISSUE TITLE
Delete automatically created closing character on backspace

### ISSUE THREAD

**Issue by lohfu** [hlissner/zsh-autopair#9]
Great plugin!

Would be nice if the automatically created closing character was deleted if the opening character is removed and they don't contain anything.

Ie, if i press `"`, immeditaly followed by backspace i would like both `"` to be removed.

EDIT: I just noticed normal backspace works just fine! but i always use Ctrl + H, which does not work.

**Comment by hlissner** [comment]
zsh-autopair now binds `^h`, so it should work now. Let me know!

**Comment by lohfu** [comment]
Works brilliantly! Thanks a lot!
